config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "articles", to: "articles#index"

  get "articles/new", to: "articles#new"

  get "articles/:id", to: "articles#show", as: :article

  post "articles", to: "articles#create"

  get "articles/:id/edit", to: "articles#edit", as: :articles_edit

  patch "articles/:id", to: "articles#update"

  delete "articles/:id", to: "articles#destroy", as: :articles_delete

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:show, :edit, :update, :destroy]


	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def show
	end

	def create
		@article = Article.create(article_params)

		redirect_to articles_path
	end

	def edit
	end

	def update
		@article.update(article_params)

		redirect_to articles_path
	end

	def destroy
		@article.destroy

		redirect_to articles_path
	end

	private

	def article_params
    params.require(:article).permit(:title, :content)
  end

	def set_article
    @article = Article.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/articles/edit.html.erb
<div class="wrapper">
	<div class="container">
		<%= render 'form', article: @article %>
	</div>
</div>

app/views/articles/index.html.erb
<div class="wrapper">
	<div class="container">
		<div class="row">
      		<div class="col-sm-8 col-sm-offset-2">
				<% @articles.each do |article| %>
					<h2> <%= link_to "#{article.title}", article_path(article)%></h2>
					<p><%= article.content %></p>
				<% end  %>
			</div>	
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<div class="wrapper">
	<div class="container">
		<%= render 'form', article: @article %>
	</div>
</div>

app/views/articles/show.html.erb
<div class="wrapper">
	<div class="container">
		<div class="row">
      		<div class="col-sm-8 col-sm-offset-2">
      			<h1><%= @article.title %></h1>
      			<%= link_to articles_edit_path do %>
                    <i class="fas fa-pencil-alt"></i>
                <% end %>
                <%= link_to articles_delete_path, method: :delete do %>
                    <i class="fas fa-trash-alt"></i>
                <% end %>
      			<hr>
      			<p><%= @article.content %></p>
      		</div>
      	</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/articles">Wikinimous</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to articles_new_path do %>
                <i class="fas fa-plus"></i>
              <% end %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </body>
</html>